export const sugars = [
  {
    name: "Dark Brown Sugar",
    color: 50,
    potential: 1.046,
    max_in_batch: 0.1,
    yield: 1.0,
    notes: "Imparts a sweet, rich flavor.",
  },
  {
    name: "Light Brown Sugar",
    color: 8,
    potential: 1.046,
    max_in_batch: 0.1,
    yield: 1.0,
    notes: "Imparts a sweet, rich flavor.",
  },
  {
    name: "Belgian Candi Syrup _ 45L",
    potential: 1.032,
    yield: 0.783,
    color: 60,
    max_in_batch: 0.2,
    notes:
      "Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales",
  },
  {
    name: "Belgian Candi Syrup _ 90L",
    yield: 0.783,
    potential: 1.032,
    color: 121,
    max_in_batch: 0.2,
    notes:
      "Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales",
  },
  {
    name: "Belgian Candi Syrup _ 180L",
    potential: 1.032,
    yield: 0.783,
    color: 243,
    max_in_batch: 0.2,
    notes:
      "Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales",
  },

  {
    name: "Clear Candi Sugar",
    potential: 1.036,
    yield: 0.783,
    color: 1,
    max_in_batch: 0.2,
    notes:
      "Crystalized candi sugar for use in Tripels, Dubbels, and holiday ales",
  },
  {
    name: "Cane Sugar",
    potential: 1.046,
    yield: 1.0,
    color: 0,
    max_in_batch: 0.07,
    notes: "Common, household sugat to lighten the flavor and body",
  },
  {
    name: "Beet Sugar",
    potential: 1.046,
    yield: 1.0,
    color: 0,
    max_in_batch: 0.07,
    notes: "Common, household sugat to lighten the flavor and body",
  },
  {
    name: "Corn Sugar",
    potential: 1.046,
    yield: 1.0,
    color: 0,
    max_in_batch: 0.05,
    notes: "Common bottling sugar",
  },
  {
    name: "Dextrose",
    potential: 1.046,
    yield: 1.0,
    color: 0,
    max_in_batch: 0.05,
    notes: "Common bottling sugar",
  },
  {
    name: "Corn Syrup",
    potential: 1.036,
    yield: 0.783,
    color: 0,
    max_in_batch: 0.1,
    notes: "Syrup derived from corn sugar",
  },
  {
    name: "Demerara Sugar",
    potential: 1.046,
    yield: 1.0,
    color: 2,
    max_in_batch: 0.1,
    notes: "A dark, unrefined sugar that contains molasses",
  },
  {
    name: "Invert Sugar",
    potential: 1.046,
    yield: 1.0,
    color: 0,
    max_in_batch: 0.1,
    notes: "A sugar used to increase starting gravity",
  },
  {
    name: "Milk Sugar",
    potential: 1.035,
    yield: 0.761,
    color: 0,
    max_in_batch: 0.1,
    notes: "A partially fermentable sugar that adds lasting sweetness",
  },
  {
    name: "Lactose",
    potential: 1.035,
    yield: 0.761,
    color: 0,
    max_in_batch: 0.1,
    notes: "A partially fermentable sugar that adds lasting sweetness",
  },
  {
    name: "Molasses",
    potential: 1.036,
    yield: 0.783,
    color: 80,
    max_in_batch: 0.05,
    notes: "A strong, dark, and sweet sugar",
  },
  {
    name: "Maple Syrup",
    potential: 1.03,
    yield: 0.652,
    color: 35,
    max_in_batch: 0.1,
    notes:
      "If added during the boil it will add a dry, woodsy flavor. If added at bottling, the smooth maple flavor comes through",
  },
  {
    name: "Table Sugar",
    potential: 1.046,
    yield: 1.0,
    color: 1,
    max_in_batch: 0.1,
    notes: "A sugar used to increase starting gravity",
  },
  {
    name: "Sucrose",
    potential: 1.046,
    yield: 1.0,
    color: 1,
    max_in_batch: 0.1,
    notes: "A sugar used to increase starting gravity",
  },
  {
    name: "Turbinado",
    potential: 1.044,
    yield: 0.957,
    color: 10,
    max_in_batch: 0.1,
    notes: "A light, raw brown sugar used to increase starting gravity",
  },
];
