export enum RecipesActionType {
  RECIPES_LOADING = "RECIPES_LOADING",
  RECIPES_FAIL = "RECIPES_FAIL",
  RECIPES_GET = "RECIPES_GET",
}

export enum UserActionType {
  SET_COOKIE = "SET_COOKIE",
  GET_USER_DATA = "GET_USER_DATA"
}